### ISSUE TITLE
Replace plus symbols with spaces in API requests

### ISSUE THREAD

**Issue by dohliam** [dohliam/yub#2]
This affects searching with the API _when it is set as the default search engine_ in both Firefox and Chrome. Spaces in the request are replaced by + signs, so a request like "g some search term" becomes "g+some+search+term" which is interpreted as a single (unrecognized) command rather than being redirected to Google.

This behaviour is the result of following this [W3C recommendation](http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) so it is unlikely to be fixed upstream.

Replacing all pluses with spaces is the obvious solution, but this breaks calc, so links like [calc 2+2](http://dohliam.github.io/yub/?calc 2+2) will no longer work. Other functions that expect a + in the input would also be affected.

Note this only afftects API requests that contain an argument in addition to a command, and only when yub.js is set as the default search engine. So default commands without arguments or spaces like [g](http://dohliam.github.io/yub/?g) or [ls](http://dohliam.github.io/yub/?ls) still work as normal.

**Comment by dohliam** [comment]
Examining the arguments passed to yub.js before they are decoded might shed some light on how to resolve this without breaking other things down the road. For example, the undecoded string passed by Firefox and Chrome to the default search engine for the terms `calc 2+2` is `calc+2%2B2`.

In other words, we _can_ distinguish between `+` as a delimiter for spaces and `%2B` which is a literal plus we want to send to the calc command. Knowing that, resolving this issue should be fairly straightforward! :wink:

**Comment by dohliam** [comment]
This is now fixed (see e659c73). The fix was complicated slightly by the fact that `decodeURI` apparently doesn't decode all non-alphanumeric characters. Critically for this bug, that includes the character `+`. Happily, there is also `decodeURIComponent` which is [more comprehensive](http://www.the-art-of-web.com/javascript/escape/):

> The encodeURIComponent function is an extension of encodeURI, the difference being that it also escapes the following characters: , / ? : @ & = + $

The newest commit using `decodeURIComponent` has been tested with Firefox and Chrome, and now works with both default search engine and keyword configurations.

**Comment by houshuang** [comment]
:+1:
